//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyPaciente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ClinicaDental")]
    public partial class PacienteDC : object
    {
        
        private string ApellidoYNombreField;
        
        private string apellidosField;
        
        private string contraseñaField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private int edadField;
        
        private int estadoField;
        
        private string estado_cadenaField;
        
        private System.DateTime fechaNacimientoField;
        
        private int idPacienteField;
        
        private int idUsuarioField;
        
        private string nombresField;
        
        private string rolField;
        
        private int sexoField;
        
        private string sexo_cadenaField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoYNombre
        {
            get
            {
                return this.ApellidoYNombreField;
            }
            set
            {
                this.ApellidoYNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this.apellidosField;
            }
            set
            {
                this.apellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña
        {
            get
            {
                return this.contraseñaField;
            }
            set
            {
                this.contraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad
        {
            get
            {
                return this.edadField;
            }
            set
            {
                this.edadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_cadena
        {
            get
            {
                return this.estado_cadenaField;
            }
            set
            {
                this.estado_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPaciente
        {
            get
            {
                return this.idPacienteField;
            }
            set
            {
                this.idPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo_cadena
        {
            get
            {
                return this.sexo_cadenaField;
            }
            set
            {
                this.sexo_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPaciente.IServicioPaciente")]
    public interface IServicioPaciente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacienteResponse")]
        ProxyPaciente.PacienteDC ConsultarPaciente(string idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ConsultarPacienteResponse")]
        System.Threading.Tasks.Task<ProxyPaciente.PacienteDC> ConsultarPacienteAsync(string idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ListarPacientes", ReplyAction="http://tempuri.org/IServicioPaciente/ListarPacientesResponse")]
        System.Collections.Generic.List<ProxyPaciente.PacienteDC> ListarPacientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ListarPacientes", ReplyAction="http://tempuri.org/IServicioPaciente/ListarPacientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyPaciente.PacienteDC>> ListarPacientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/agregarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/agregarPacienteResponse")]
        bool agregarPaciente(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/agregarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/agregarPacienteResponse")]
        System.Threading.Tasks.Task<bool> agregarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ActualizarPacienteResponse")]
        bool ActualizarPaciente(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/ActualizarPacienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/EliminarPacienteResponse")]
        bool EliminarPaciente(string idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/EliminarPacienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarPacienteAsync(string idPaciente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioPacienteChannel : ProxyPaciente.IServicioPaciente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioPacienteClient : System.ServiceModel.ClientBase<ProxyPaciente.IServicioPaciente>, ProxyPaciente.IServicioPaciente
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioPacienteClient() : 
                base(ServicioPacienteClient.GetDefaultBinding(), ServicioPacienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioPaciente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioPacienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyPaciente.PacienteDC ConsultarPaciente(string idPaciente)
        {
            return base.Channel.ConsultarPaciente(idPaciente);
        }
        
        public System.Threading.Tasks.Task<ProxyPaciente.PacienteDC> ConsultarPacienteAsync(string idPaciente)
        {
            return base.Channel.ConsultarPacienteAsync(idPaciente);
        }
        
        public System.Collections.Generic.List<ProxyPaciente.PacienteDC> ListarPacientes()
        {
            return base.Channel.ListarPacientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyPaciente.PacienteDC>> ListarPacientesAsync()
        {
            return base.Channel.ListarPacientesAsync();
        }
        
        public bool agregarPaciente(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.agregarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> agregarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.agregarPacienteAsync(objPacienteDC);
        }
        
        public bool ActualizarPaciente(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.ActualizarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.ActualizarPacienteAsync(objPacienteDC);
        }
        
        public bool EliminarPaciente(string idPaciente)
        {
            return base.Channel.EliminarPaciente(idPaciente);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPacienteAsync(string idPaciente)
        {
            return base.Channel.EliminarPacienteAsync(idPaciente);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPaciente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPaciente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ClinicaDental/ServicioPaciente/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioPacienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioPaciente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioPacienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioPaciente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioPaciente,
        }
    }
}
