//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyDentista
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DentistaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ClinicaDental")]
    public partial class DentistaDC : object
    {
        
        private string ApellidoYNombreField;
        
        private string apellidosField;
        
        private string contraseñaField;
        
        private string correoField;
        
        private string direccionField;
        
        private string dniField;
        
        private int edadField;
        
        private int estadoField;
        
        private int estadoDentistaField;
        
        private int estadoDentistaUsuarioField;
        
        private string estadoDentistaUsuario_cadenaField;
        
        private string estadoDentista_cadenaField;
        
        private System.DateTime fechaNacimientoField;
        
        private int idDentistaField;
        
        private int idEspecialidadField;
        
        private int idUsuarioField;
        
        private string nombreEspecialidadField;
        
        private string nombresField;
        
        private string rolField;
        
        private int sexoField;
        
        private string sexo_cadenaField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoYNombre
        {
            get
            {
                return this.ApellidoYNombreField;
            }
            set
            {
                this.ApellidoYNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this.apellidosField;
            }
            set
            {
                this.apellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña
        {
            get
            {
                return this.contraseñaField;
            }
            set
            {
                this.contraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad
        {
            get
            {
                return this.edadField;
            }
            set
            {
                this.edadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estadoDentista
        {
            get
            {
                return this.estadoDentistaField;
            }
            set
            {
                this.estadoDentistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estadoDentistaUsuario
        {
            get
            {
                return this.estadoDentistaUsuarioField;
            }
            set
            {
                this.estadoDentistaUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoDentistaUsuario_cadena
        {
            get
            {
                return this.estadoDentistaUsuario_cadenaField;
            }
            set
            {
                this.estadoDentistaUsuario_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoDentista_cadena
        {
            get
            {
                return this.estadoDentista_cadenaField;
            }
            set
            {
                this.estadoDentista_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDentista
        {
            get
            {
                return this.idDentistaField;
            }
            set
            {
                this.idDentistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEspecialidad
        {
            get
            {
                return this.idEspecialidadField;
            }
            set
            {
                this.idEspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreEspecialidad
        {
            get
            {
                return this.nombreEspecialidadField;
            }
            set
            {
                this.nombreEspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo_cadena
        {
            get
            {
                return this.sexo_cadenaField;
            }
            set
            {
                this.sexo_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisponibilidadDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ClinicaDental")]
    public partial class DisponibilidadDC : object
    {
        
        private string diaSemanaField;
        
        private int estadoField;
        
        private string estado_cadenaField;
        
        private System.DateTime fechaField;
        
        private System.TimeSpan horaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaSemana
        {
            get
            {
                return this.diaSemanaField;
            }
            set
            {
                this.diaSemanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_cadena
        {
            get
            {
                return this.estado_cadenaField;
            }
            set
            {
                this.estado_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyDentista.IServicioDentista")]
    public interface IServicioDentista
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ListarDentistasPorEspecialidad", ReplyAction="http://tempuri.org/IServicioDentista/ListarDentistasPorEspecialidadResponse")]
        System.Collections.Generic.List<ProxyDentista.DentistaDC> ListarDentistasPorEspecialidad(string idEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ListarDentistasPorEspecialidad", ReplyAction="http://tempuri.org/IServicioDentista/ListarDentistasPorEspecialidadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDentista.DentistaDC>> ListarDentistasPorEspecialidadAsync(string idEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ConsultarDisponibilidadDetallada", ReplyAction="http://tempuri.org/IServicioDentista/ConsultarDisponibilidadDetalladaResponse")]
        System.Collections.Generic.List<ProxyDentista.DisponibilidadDC> ConsultarDisponibilidadDetallada(string idDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ConsultarDisponibilidadDetallada", ReplyAction="http://tempuri.org/IServicioDentista/ConsultarDisponibilidadDetalladaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDentista.DisponibilidadDC>> ConsultarDisponibilidadDetalladaAsync(string idDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ConsultarDentista", ReplyAction="http://tempuri.org/IServicioDentista/ConsultarDentistaResponse")]
        ProxyDentista.DentistaDC ConsultarDentista(string idDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ConsultarDentista", ReplyAction="http://tempuri.org/IServicioDentista/ConsultarDentistaResponse")]
        System.Threading.Tasks.Task<ProxyDentista.DentistaDC> ConsultarDentistaAsync(string idDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ListarDentistas", ReplyAction="http://tempuri.org/IServicioDentista/ListarDentistasResponse")]
        System.Collections.Generic.List<ProxyDentista.DentistaDC> ListarDentistas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ListarDentistas", ReplyAction="http://tempuri.org/IServicioDentista/ListarDentistasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDentista.DentistaDC>> ListarDentistasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/AgregarDentista", ReplyAction="http://tempuri.org/IServicioDentista/AgregarDentistaResponse")]
        bool AgregarDentista(ProxyDentista.DentistaDC objDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/AgregarDentista", ReplyAction="http://tempuri.org/IServicioDentista/AgregarDentistaResponse")]
        System.Threading.Tasks.Task<bool> AgregarDentistaAsync(ProxyDentista.DentistaDC objDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ActualizarDentista", ReplyAction="http://tempuri.org/IServicioDentista/ActualizarDentistaResponse")]
        bool ActualizarDentista(ProxyDentista.DentistaDC objDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/ActualizarDentista", ReplyAction="http://tempuri.org/IServicioDentista/ActualizarDentistaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarDentistaAsync(ProxyDentista.DentistaDC objDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/EliminarDentista", ReplyAction="http://tempuri.org/IServicioDentista/EliminarDentistaResponse")]
        bool EliminarDentista(string idDentista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDentista/EliminarDentista", ReplyAction="http://tempuri.org/IServicioDentista/EliminarDentistaResponse")]
        System.Threading.Tasks.Task<bool> EliminarDentistaAsync(string idDentista);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioDentistaChannel : ProxyDentista.IServicioDentista, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioDentistaClient : System.ServiceModel.ClientBase<ProxyDentista.IServicioDentista>, ProxyDentista.IServicioDentista
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioDentistaClient() : 
                base(ServicioDentistaClient.GetDefaultBinding(), ServicioDentistaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioDentista.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDentistaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioDentistaClient.GetBindingForEndpoint(endpointConfiguration), ServicioDentistaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDentistaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioDentistaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDentistaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioDentistaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDentistaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyDentista.DentistaDC> ListarDentistasPorEspecialidad(string idEspecialidad)
        {
            return base.Channel.ListarDentistasPorEspecialidad(idEspecialidad);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDentista.DentistaDC>> ListarDentistasPorEspecialidadAsync(string idEspecialidad)
        {
            return base.Channel.ListarDentistasPorEspecialidadAsync(idEspecialidad);
        }
        
        public System.Collections.Generic.List<ProxyDentista.DisponibilidadDC> ConsultarDisponibilidadDetallada(string idDentista)
        {
            return base.Channel.ConsultarDisponibilidadDetallada(idDentista);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDentista.DisponibilidadDC>> ConsultarDisponibilidadDetalladaAsync(string idDentista)
        {
            return base.Channel.ConsultarDisponibilidadDetalladaAsync(idDentista);
        }
        
        public ProxyDentista.DentistaDC ConsultarDentista(string idDentista)
        {
            return base.Channel.ConsultarDentista(idDentista);
        }
        
        public System.Threading.Tasks.Task<ProxyDentista.DentistaDC> ConsultarDentistaAsync(string idDentista)
        {
            return base.Channel.ConsultarDentistaAsync(idDentista);
        }
        
        public System.Collections.Generic.List<ProxyDentista.DentistaDC> ListarDentistas()
        {
            return base.Channel.ListarDentistas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDentista.DentistaDC>> ListarDentistasAsync()
        {
            return base.Channel.ListarDentistasAsync();
        }
        
        public bool AgregarDentista(ProxyDentista.DentistaDC objDentista)
        {
            return base.Channel.AgregarDentista(objDentista);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarDentistaAsync(ProxyDentista.DentistaDC objDentista)
        {
            return base.Channel.AgregarDentistaAsync(objDentista);
        }
        
        public bool ActualizarDentista(ProxyDentista.DentistaDC objDentista)
        {
            return base.Channel.ActualizarDentista(objDentista);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarDentistaAsync(ProxyDentista.DentistaDC objDentista)
        {
            return base.Channel.ActualizarDentistaAsync(objDentista);
        }
        
        public bool EliminarDentista(string idDentista)
        {
            return base.Channel.EliminarDentista(idDentista);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDentistaAsync(string idDentista)
        {
            return base.Channel.EliminarDentistaAsync(idDentista);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioDentista))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioDentista))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ClinicaDental/ServicioDentista/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioDentistaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioDentista);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioDentistaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioDentista);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioDentista,
        }
    }
}
