//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCita
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CitaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ClinicaDental")]
    public partial class CitaDC : object
    {
        
        private string apellidoPacienteField;
        
        private int añoField;
        
        private string correoPacienteField;
        
        private string descripcionField;
        
        private string diaSemanaField;
        
        private string direccionPacienteField;
        
        private string dniField;
        
        private int edadPacienteField;
        
        private int estadoField;
        
        private string estado_cadenaField;
        
        private System.DateTime fechaField;
        
        private System.DateTime fechaCitaField;
        
        private System.DateTime fechaNacimientoPacienteField;
        
        private System.TimeSpan horaCitaField;
        
        private string horarioDentistaField;
        
        private System.TimeSpan horarioFinField;
        
        private System.TimeSpan horarioInicioField;
        
        private int idCitaField;
        
        private int idDentistaField;
        
        private int idHistoriaClinicaField;
        
        private int idPacienteField;
        
        private int idTratamientoField;
        
        private int mesField;
        
        private string motivoField;
        
        private string motivoCitaField;
        
        private string nombreDentistaField;
        
        private string nombreEspecialidadField;
        
        private string nombrePacienteField;
        
        private string nombreTratamientoField;
        
        private string observacionesField;
        
        private int sexoField;
        
        private string sexo_cadenaField;
        
        private string telefonoPacienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaciente
        {
            get
            {
                return this.apellidoPacienteField;
            }
            set
            {
                this.apellidoPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int año
        {
            get
            {
                return this.añoField;
            }
            set
            {
                this.añoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoPaciente
        {
            get
            {
                return this.correoPacienteField;
            }
            set
            {
                this.correoPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaSemana
        {
            get
            {
                return this.diaSemanaField;
            }
            set
            {
                this.diaSemanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccionPaciente
        {
            get
            {
                return this.direccionPacienteField;
            }
            set
            {
                this.direccionPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edadPaciente
        {
            get
            {
                return this.edadPacienteField;
            }
            set
            {
                this.edadPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_cadena
        {
            get
            {
                return this.estado_cadenaField;
            }
            set
            {
                this.estado_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaCita
        {
            get
            {
                return this.fechaCitaField;
            }
            set
            {
                this.fechaCitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimientoPaciente
        {
            get
            {
                return this.fechaNacimientoPacienteField;
            }
            set
            {
                this.fechaNacimientoPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horaCita
        {
            get
            {
                return this.horaCitaField;
            }
            set
            {
                this.horaCitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horarioDentista
        {
            get
            {
                return this.horarioDentistaField;
            }
            set
            {
                this.horarioDentistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horarioFin
        {
            get
            {
                return this.horarioFinField;
            }
            set
            {
                this.horarioFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horarioInicio
        {
            get
            {
                return this.horarioInicioField;
            }
            set
            {
                this.horarioInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCita
        {
            get
            {
                return this.idCitaField;
            }
            set
            {
                this.idCitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDentista
        {
            get
            {
                return this.idDentistaField;
            }
            set
            {
                this.idDentistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHistoriaClinica
        {
            get
            {
                return this.idHistoriaClinicaField;
            }
            set
            {
                this.idHistoriaClinicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPaciente
        {
            get
            {
                return this.idPacienteField;
            }
            set
            {
                this.idPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTratamiento
        {
            get
            {
                return this.idTratamientoField;
            }
            set
            {
                this.idTratamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mes
        {
            get
            {
                return this.mesField;
            }
            set
            {
                this.mesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motivoCita
        {
            get
            {
                return this.motivoCitaField;
            }
            set
            {
                this.motivoCitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreDentista
        {
            get
            {
                return this.nombreDentistaField;
            }
            set
            {
                this.nombreDentistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreEspecialidad
        {
            get
            {
                return this.nombreEspecialidadField;
            }
            set
            {
                this.nombreEspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePaciente
        {
            get
            {
                return this.nombrePacienteField;
            }
            set
            {
                this.nombrePacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreTratamiento
        {
            get
            {
                return this.nombreTratamientoField;
            }
            set
            {
                this.nombreTratamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo_cadena
        {
            get
            {
                return this.sexo_cadenaField;
            }
            set
            {
                this.sexo_cadenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoPaciente
        {
            get
            {
                return this.telefonoPacienteField;
            }
            set
            {
                this.telefonoPacienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalendarioDisponibleDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ClinicaDental")]
    public partial class CalendarioDisponibleDC : object
    {
        
        private string DomingoField;
        
        private System.TimeSpan HoraField;
        
        private string JuevesField;
        
        private string LunesField;
        
        private string MartesField;
        
        private string MiércolesField;
        
        private string SábadoField;
        
        private string ViernesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domingo
        {
            get
            {
                return this.DomingoField;
            }
            set
            {
                this.DomingoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jueves
        {
            get
            {
                return this.JuevesField;
            }
            set
            {
                this.JuevesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lunes
        {
            get
            {
                return this.LunesField;
            }
            set
            {
                this.LunesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Martes
        {
            get
            {
                return this.MartesField;
            }
            set
            {
                this.MartesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Miércoles
        {
            get
            {
                return this.MiércolesField;
            }
            set
            {
                this.MiércolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sábado
        {
            get
            {
                return this.SábadoField;
            }
            set
            {
                this.SábadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Viernes
        {
            get
            {
                return this.ViernesField;
            }
            set
            {
                this.ViernesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCita.IServicioCita")]
    public interface IServicioCita
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/AgregarCita", ReplyAction="http://tempuri.org/IServicioCita/AgregarCitaResponse")]
        bool AgregarCita(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/AgregarCita", ReplyAction="http://tempuri.org/IServicioCita/AgregarCitaResponse")]
        System.Threading.Tasks.Task<bool> AgregarCitaAsync(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPaciente", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPacienteResponse")]
        System.Collections.Generic.List<ProxyCita.CitaDC> ListarCitasPaciente(string idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPaciente", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPacienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CitaDC>> ListarCitasPacienteAsync(string idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/CancelarCita", ReplyAction="http://tempuri.org/IServicioCita/CancelarCitaResponse")]
        bool CancelarCita(string idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/CancelarCita", ReplyAction="http://tempuri.org/IServicioCita/CancelarCitaResponse")]
        System.Threading.Tasks.Task<bool> CancelarCitaAsync(string idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ListarHistoriaClinicaResponse")]
        System.Collections.Generic.List<ProxyCita.CitaDC> ListarHistoriaClinica(string idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ListarHistoriaClinicaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CitaDC>> ListarHistoriaClinicaAsync(string idPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPorDentistaYFecha", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPorDentistaYFechaResponse")]
        System.Collections.Generic.List<ProxyCita.CitaDC> ListarCitasPorDentistaYFecha(string idDentista, System.DateTime fechaInicio, System.Nullable<System.DateTime> fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ListarCitasPorDentistaYFecha", ReplyAction="http://tempuri.org/IServicioCita/ListarCitasPorDentistaYFechaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CitaDC>> ListarCitasPorDentistaYFechaAsync(string idDentista, System.DateTime fechaInicio, System.Nullable<System.DateTime> fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/AgregarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/AgregarHistoriaClinicaResponse")]
        bool AgregarHistoriaClinica(ProxyCita.CitaDC CitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/AgregarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/AgregarHistoriaClinicaResponse")]
        System.Threading.Tasks.Task<bool> AgregarHistoriaClinicaAsync(ProxyCita.CitaDC CitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ActualizarEstadoCita", ReplyAction="http://tempuri.org/IServicioCita/ActualizarEstadoCitaResponse")]
        bool ActualizarEstadoCita(int idCita, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ActualizarEstadoCita", ReplyAction="http://tempuri.org/IServicioCita/ActualizarEstadoCitaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstadoCitaAsync(int idCita, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ExisteHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ExisteHistoriaClinicaResponse")]
        bool ExisteHistoriaClinica(int idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ExisteHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ExisteHistoriaClinicaResponse")]
        System.Threading.Tasks.Task<bool> ExisteHistoriaClinicaAsync(int idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ConsultarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ConsultarHistoriaClinicaResponse")]
        ProxyCita.CitaDC ConsultarHistoriaClinica(string idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ConsultarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ConsultarHistoriaClinicaResponse")]
        System.Threading.Tasks.Task<ProxyCita.CitaDC> ConsultarHistoriaClinicaAsync(string idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ActualizarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ActualizarHistoriaClinicaResponse")]
        bool ActualizarHistoriaClinica(ProxyCita.CitaDC objCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ActualizarHistoriaClinica", ReplyAction="http://tempuri.org/IServicioCita/ActualizarHistoriaClinicaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarHistoriaClinicaAsync(ProxyCita.CitaDC objCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ObtenerCalendarioDisponible", ReplyAction="http://tempuri.org/IServicioCita/ObtenerCalendarioDisponibleResponse")]
        System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC> ObtenerCalendarioDisponible(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ObtenerCalendarioDisponible", ReplyAction="http://tempuri.org/IServicioCita/ObtenerCalendarioDisponibleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC>> ObtenerCalendarioDisponibleAsync(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/AgregarHorarioDentista", ReplyAction="http://tempuri.org/IServicioCita/AgregarHorarioDentistaResponse")]
        bool AgregarHorarioDentista(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/AgregarHorarioDentista", ReplyAction="http://tempuri.org/IServicioCita/AgregarHorarioDentistaResponse")]
        System.Threading.Tasks.Task<bool> AgregarHorarioDentistaAsync(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ObtenerHorarioDentista", ReplyAction="http://tempuri.org/IServicioCita/ObtenerHorarioDentistaResponse")]
        System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC> ObtenerHorarioDentista(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ObtenerHorarioDentista", ReplyAction="http://tempuri.org/IServicioCita/ObtenerHorarioDentistaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC>> ObtenerHorarioDentistaAsync(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ObtenerHorarioDetallado", ReplyAction="http://tempuri.org/IServicioCita/ObtenerHorarioDetalladoResponse")]
        System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC> ObtenerHorarioDetallado(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/ObtenerHorarioDetallado", ReplyAction="http://tempuri.org/IServicioCita/ObtenerHorarioDetalladoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC>> ObtenerHorarioDetalladoAsync(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarDisponibilidadDentista", ReplyAction="http://tempuri.org/IServicioCita/EliminarDisponibilidadDentistaResponse")]
        bool EliminarDisponibilidadDentista(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarDisponibilidadDentista", ReplyAction="http://tempuri.org/IServicioCita/EliminarDisponibilidadDentistaResponse")]
        System.Threading.Tasks.Task<bool> EliminarDisponibilidadDentistaAsync(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarDisponibilidadDia", ReplyAction="http://tempuri.org/IServicioCita/EliminarDisponibilidadDiaResponse")]
        bool EliminarDisponibilidadDia(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarDisponibilidadDia", ReplyAction="http://tempuri.org/IServicioCita/EliminarDisponibilidadDiaResponse")]
        System.Threading.Tasks.Task<bool> EliminarDisponibilidadDiaAsync(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarHorarioDentistaHora", ReplyAction="http://tempuri.org/IServicioCita/EliminarHorarioDentistaHoraResponse")]
        bool EliminarHorarioDentistaHora(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarHorarioDentistaHora", ReplyAction="http://tempuri.org/IServicioCita/EliminarHorarioDentistaHoraResponse")]
        System.Threading.Tasks.Task<bool> EliminarHorarioDentistaHoraAsync(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarHorarioDentistaDia", ReplyAction="http://tempuri.org/IServicioCita/EliminarHorarioDentistaDiaResponse")]
        bool EliminarHorarioDentistaDia(ProxyCita.CitaDC objCitaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCita/EliminarHorarioDentistaDia", ReplyAction="http://tempuri.org/IServicioCita/EliminarHorarioDentistaDiaResponse")]
        System.Threading.Tasks.Task<bool> EliminarHorarioDentistaDiaAsync(ProxyCita.CitaDC objCitaDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioCitaChannel : ProxyCita.IServicioCita, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioCitaClient : System.ServiceModel.ClientBase<ProxyCita.IServicioCita>, ProxyCita.IServicioCita
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioCitaClient() : 
                base(ServicioCitaClient.GetDefaultBinding(), ServicioCitaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCita.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioCitaClient.GetBindingForEndpoint(endpointConfiguration), ServicioCitaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioCitaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioCitaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCitaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AgregarCita(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.AgregarCita(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarCitaAsync(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.AgregarCitaAsync(objCitaDC);
        }
        
        public System.Collections.Generic.List<ProxyCita.CitaDC> ListarCitasPaciente(string idCita)
        {
            return base.Channel.ListarCitasPaciente(idCita);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CitaDC>> ListarCitasPacienteAsync(string idCita)
        {
            return base.Channel.ListarCitasPacienteAsync(idCita);
        }
        
        public bool CancelarCita(string idCita)
        {
            return base.Channel.CancelarCita(idCita);
        }
        
        public System.Threading.Tasks.Task<bool> CancelarCitaAsync(string idCita)
        {
            return base.Channel.CancelarCitaAsync(idCita);
        }
        
        public System.Collections.Generic.List<ProxyCita.CitaDC> ListarHistoriaClinica(string idPaciente)
        {
            return base.Channel.ListarHistoriaClinica(idPaciente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CitaDC>> ListarHistoriaClinicaAsync(string idPaciente)
        {
            return base.Channel.ListarHistoriaClinicaAsync(idPaciente);
        }
        
        public System.Collections.Generic.List<ProxyCita.CitaDC> ListarCitasPorDentistaYFecha(string idDentista, System.DateTime fechaInicio, System.Nullable<System.DateTime> fechaFin)
        {
            return base.Channel.ListarCitasPorDentistaYFecha(idDentista, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CitaDC>> ListarCitasPorDentistaYFechaAsync(string idDentista, System.DateTime fechaInicio, System.Nullable<System.DateTime> fechaFin)
        {
            return base.Channel.ListarCitasPorDentistaYFechaAsync(idDentista, fechaInicio, fechaFin);
        }
        
        public bool AgregarHistoriaClinica(ProxyCita.CitaDC CitaDC)
        {
            return base.Channel.AgregarHistoriaClinica(CitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarHistoriaClinicaAsync(ProxyCita.CitaDC CitaDC)
        {
            return base.Channel.AgregarHistoriaClinicaAsync(CitaDC);
        }
        
        public bool ActualizarEstadoCita(int idCita, int estado)
        {
            return base.Channel.ActualizarEstadoCita(idCita, estado);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstadoCitaAsync(int idCita, int estado)
        {
            return base.Channel.ActualizarEstadoCitaAsync(idCita, estado);
        }
        
        public bool ExisteHistoriaClinica(int idCita)
        {
            return base.Channel.ExisteHistoriaClinica(idCita);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteHistoriaClinicaAsync(int idCita)
        {
            return base.Channel.ExisteHistoriaClinicaAsync(idCita);
        }
        
        public ProxyCita.CitaDC ConsultarHistoriaClinica(string idCita)
        {
            return base.Channel.ConsultarHistoriaClinica(idCita);
        }
        
        public System.Threading.Tasks.Task<ProxyCita.CitaDC> ConsultarHistoriaClinicaAsync(string idCita)
        {
            return base.Channel.ConsultarHistoriaClinicaAsync(idCita);
        }
        
        public bool ActualizarHistoriaClinica(ProxyCita.CitaDC objCita)
        {
            return base.Channel.ActualizarHistoriaClinica(objCita);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarHistoriaClinicaAsync(ProxyCita.CitaDC objCita)
        {
            return base.Channel.ActualizarHistoriaClinicaAsync(objCita);
        }
        
        public System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC> ObtenerCalendarioDisponible(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio)
        {
            return base.Channel.ObtenerCalendarioDisponible(idDentista, fechaInicio);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC>> ObtenerCalendarioDisponibleAsync(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio)
        {
            return base.Channel.ObtenerCalendarioDisponibleAsync(idDentista, fechaInicio);
        }
        
        public bool AgregarHorarioDentista(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.AgregarHorarioDentista(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarHorarioDentistaAsync(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.AgregarHorarioDentistaAsync(objCitaDC);
        }
        
        public System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC> ObtenerHorarioDentista(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio)
        {
            return base.Channel.ObtenerHorarioDentista(idDentista, fechaInicio);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC>> ObtenerHorarioDentistaAsync(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio)
        {
            return base.Channel.ObtenerHorarioDentistaAsync(idDentista, fechaInicio);
        }
        
        public System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC> ObtenerHorarioDetallado(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio)
        {
            return base.Channel.ObtenerHorarioDetallado(idDentista, fechaInicio);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCita.CalendarioDisponibleDC>> ObtenerHorarioDetalladoAsync(System.Nullable<int> idDentista, System.Nullable<System.DateTime> fechaInicio)
        {
            return base.Channel.ObtenerHorarioDetalladoAsync(idDentista, fechaInicio);
        }
        
        public bool EliminarDisponibilidadDentista(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarDisponibilidadDentista(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDisponibilidadDentistaAsync(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarDisponibilidadDentistaAsync(objCitaDC);
        }
        
        public bool EliminarDisponibilidadDia(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarDisponibilidadDia(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDisponibilidadDiaAsync(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarDisponibilidadDiaAsync(objCitaDC);
        }
        
        public bool EliminarHorarioDentistaHora(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarHorarioDentistaHora(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarHorarioDentistaHoraAsync(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarHorarioDentistaHoraAsync(objCitaDC);
        }
        
        public bool EliminarHorarioDentistaDia(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarHorarioDentistaDia(objCitaDC);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarHorarioDentistaDiaAsync(ProxyCita.CitaDC objCitaDC)
        {
            return base.Channel.EliminarHorarioDentistaDiaAsync(objCitaDC);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCita))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCita))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ClinicaDental/ServicioCita/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioCitaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCita);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioCitaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCita);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCita,
        }
    }
}
