//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ClinicaDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Historia = new HashSet<Historia>();
        }
    
        public int idCita { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idDentista { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public Nullable<System.TimeSpan> horaCita { get; set; }
        public string motivoCita { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Dentista Dentista { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia> Historia { get; set; }
    }
}
