//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ClinicaDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        public int idDisponibilidad { get; set; }
        public Nullable<int> idDentista { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> estado { get; set; }
        public string MotivoEliminacion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Dentista Dentista { get; set; }
    }
}
