//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ClinicaDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioDentista
    {
        public int idHorario { get; set; }
        public Nullable<int> idDentista { get; set; }
        public string diaSemana { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
        public Nullable<int> mesObjetivo { get; set; }
        public Nullable<int> anioObjetivo { get; set; }
    
        public virtual Dentista Dentista { get; set; }
    }
}
