//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyTratamiento
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TratamientoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ClinicaDental")]
    public partial class TratamientoDC : object
    {
        
        private string descripcionField;
        
        private int idTratamientoField;
        
        private string nombreField;
        
        private decimal precioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTratamiento
        {
            get
            {
                return this.idTratamientoField;
            }
            set
            {
                this.idTratamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTratamiento.IServicioTratamiento")]
    public interface IServicioTratamiento
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTratamiento/ListarTratamientos", ReplyAction="http://tempuri.org/IServicioTratamiento/ListarTratamientosResponse")]
        System.Collections.Generic.List<ProxyTratamiento.TratamientoDC> ListarTratamientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTratamiento/ListarTratamientos", ReplyAction="http://tempuri.org/IServicioTratamiento/ListarTratamientosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyTratamiento.TratamientoDC>> ListarTratamientosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioTratamientoChannel : ProxyTratamiento.IServicioTratamiento, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioTratamientoClient : System.ServiceModel.ClientBase<ProxyTratamiento.IServicioTratamiento>, ProxyTratamiento.IServicioTratamiento
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioTratamientoClient() : 
                base(ServicioTratamientoClient.GetDefaultBinding(), ServicioTratamientoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioTratamiento.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTratamientoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioTratamientoClient.GetBindingForEndpoint(endpointConfiguration), ServicioTratamientoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTratamientoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioTratamientoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTratamientoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioTratamientoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioTratamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyTratamiento.TratamientoDC> ListarTratamientos()
        {
            return base.Channel.ListarTratamientos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyTratamiento.TratamientoDC>> ListarTratamientosAsync()
        {
            return base.Channel.ListarTratamientosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTratamiento))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioTratamiento))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ClinicaDental/ServicioTratamiento" +
                        "/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioTratamientoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioTratamiento);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioTratamientoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioTratamiento);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioTratamiento,
        }
    }
}
